#include <stdio.h>
#include <stdint.h>
#include "memory.h"

unsigned char Instruction[256];
unsigned char Data[4096]; 

void initialize() {
    // DYNAMIC PATH: Reads the bytecode generated by your compiler
    FILE *prog_file = fopen("program.byte", "r");
    if (prog_file) {
        int op, d, s1, s2;
        int i = 0;
        while (fscanf(prog_file, "%x %x %x %x", &op, &d, &s1, &s2) == 4) {
            if (i >= 252) break; // Crash prevention
            Instruction[i++] = (unsigned char)op;
            Instruction[i++] = (unsigned char)d;
            Instruction[i++] = (unsigned char)s1;
            Instruction[i++] = (unsigned char)s2;
        }
        fclose(prog_file);
    }
    
    // DYNAMIC PATH: Reads your memory data
    FILE *data_file = fopen("data.byte", "r");
    int has_data = 0;
    
    if (data_file) {
        int op, d, s1, s2;
        int i = 0;
        while (fscanf(data_file, "%x %x %x %x", &op, &d, &s1, &s2) == 4) {
            if (i >= 4092) break; // Crash prevention
            Data[i++] = (unsigned char)op;
            Data[i++] = (unsigned char)d;
            Data[i++] = (unsigned char)s1;
            Data[i++] = (unsigned char)s2;
            
            // Check if there are actual numbers in the file (not just zeros)
            if (op != 0 || d != 0 || s1 != 0 || s2 != 0) {
                has_data = 1;
            }
        }
        fclose(data_file);
    }

    // AUTO-LOADER: If data.byte was empty or full of zeros, inject the test array!
    if (has_data == 0) {
        printf("[System Warning] data.byte was empty! Injecting default test array (Size 3)...\n");
        Data[3] = 0x03;  // Array Size = 3
        Data[7] = 0x0A;  // Element 1 = 10
        Data[11] = 0x14; // Element 2 = 20
        Data[15] = 0x1E; // Element 3 = 30
    }
}

void finalize() {
    // Saves the final output back to the file
    FILE *data_file = fopen("data.byte", "w");
    if (data_file) {
        for (int i = 0; i < 4096; i += 4) {
            fprintf(data_file, "%02X %02X %02X %02X\n", Data[i], Data[i+1], Data[i+2], Data[i+3]);
        }
        fclose(data_file);
    }
}