#include <stdio.h>
#include <stdint.h>
#include "memory.h"

unsigned char Instruction[256];
unsigned char Data[4096]; 

void initialize() {
    // DYNAMIC PATH: Reads the bytecode generated by your compiler
    FILE *prog_file = fopen("program.byte", "r");
    if (prog_file) {
        int op, d, s1, s2;
        int i = 0;
        // CHANGED TO %d: The spec explicitly requires decimal bytecodes!
        while (fscanf(prog_file, "%d %d %d %d", &op, &d, &s1, &s2) == 4) {
            if (i >= 252) break; // Crash prevention
            Instruction[i++] = (unsigned char)op;
            Instruction[i++] = (unsigned char)d;
            Instruction[i++] = (unsigned char)s1;
            Instruction[i++] = (unsigned char)s2;
        }
        fclose(prog_file);
    }
    
    // DYNAMIC PATH: Reads your memory data
    FILE *data_file = fopen("data.byte", "r");
    int has_data = 0;
    
    if (data_file) {
        int op, d, s1, s2;
        int i = 0;
        // CHANGED TO %i: This magically reads BOTH decimal and hex automatically
        while (fscanf(data_file, "%i %i %i %i", &op, &d, &s1, &s2) == 4) {
            if (i >= 4092) break; // Crash prevention
            Data[i++] = (unsigned char)op;
            Data[i++] = (unsigned char)d;
            Data[i++] = (unsigned char)s1;
            Data[i++] = (unsigned char)s2;
            
            // Check if there are actual numbers in the file (not just zeros)
            if (op != 0 || d != 0 || s1 != 0 || s2 != 0) {
                has_data = 1;
            }
        }
        fclose(data_file);
    }

    // VECTOR AUTO-LOADER: If data.byte is empty, inject SIMD test arrays!
    if (has_data == 0) {
        printf("[System Warning] data.byte empty! Injecting Vector Test Arrays (N=8)...\n");
        
        Data[0] = 8; // Array Size N = 8
        
        // Inject Array A at address 0x4 (1, 2, 3, 4, 5, 6, 7, 8)
        for(int i = 0; i < 8; i++) {
            Data[4 + (i * 4)] = i + 1; 
        }
        
        // Inject Array B at address 36 (10, 20, 30, 40, 50, 60, 70, 80)
        for(int i = 0; i < 8; i++) {
            Data[36 + (i * 4)] = (i + 1) * 10; 
        }
    }
}

void finalize() {
    // Saves the final output back to the file
    FILE *data_file = fopen("data.byte", "w");
    if (data_file) {
        for (int i = 0; i < 4096; i += 4) {
            // Write it out as decimal to match the strict spec format
            fprintf(data_file, "%d %d %d %d\n", Data[i], Data[i+1], Data[i+2], Data[i+3]);
        }
        fclose(data_file);
    }
}